apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fhir-data-dstu2
  name: fhir-data-dstu2
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9002
      targetPort: 9002
      protocol: TCP
  selector:
    io.kompose.service: fhir-data-dstu2
